package ua.lpnu.kzp;

import java.io.IOException;
import java.io.InputStream;
import java.util.Properties;

/** Reads version metadata generated by Maven during the build. */
public final class BuildInfo {
    private static final String RESOURCE_NAME = "/build-info.properties";

    private BuildInfo() {
    }

    /**
     * Loads the product name, product version, and CI build number.
     *
     * @return immutable build metadata for CLI output
     */
    public static Properties load() {
        Properties properties = new Properties();
        try (InputStream stream = BuildInfo.class.getResourceAsStream(RESOURCE_NAME)) {
            if (stream == null) {
                throw new IllegalStateException("Build metadata resource is missing");
            }
            properties.load(stream);
            return properties;
        } catch (IOException exception) {
            throw new IllegalStateException("Build metadata cannot be read", exception);
        }
    }
}
